/**
 * NYC Mock Adapter - Realistic sample data for demo purposes
 *
 * This adapter provides hardcoded mock data for NYC swim lessons across
 * multiple providers, locations, and boroughs. Used for development,
 * testing, and product demos.
 */

import { BaseAdapter, SessionFilters } from '@core/contracts/city-adapter';
import {
  Provider,
  Location,
  Program,
  Session,
  SyncResult,
  ValidationResult,
  TransitEstimate,
} from '@core/models/canonical-schema';
import { Coordinates, TransitMode, CityConfig } from '@core/contracts/city-config';

/**
 * NYC Mock Adapter
 *
 * Provides realistic sample data with:
 * - 5 providers (NYC Parks, YMCA Brooklyn, JCC Manhattan, Asphalt Green, Elite Swim Academy)
 * - 8 locations across Manhattan, Brooklyn, Queens
 * - 11 programs (various skill levels and age groups)
 * - 28 sessions (June-August 2026 summer sessions)
 */
export class NYCMockAdapter extends BaseAdapter {
  private config: CityConfig;

  constructor(cityId: string, config: CityConfig) {
    super(cityId);
    this.config = config;
  }

  /**
   * Get all mock locations across NYC boroughs
   */
  async getLocations(): Promise<Location[]> {
    const locations: Location[] = [
      // Manhattan Locations
      {
        id: 'loc-001',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-001',
        name: 'Hamilton Fish Pool',
        address: {
          street: '128 East Houston Street',
          city: 'New York',
          state: 'NY',
          zipCode: '10002',
          geographyId: 'manhattan',
        },
        coordinates: { latitude: 40.7157, longitude: -73.9806 },
        facilityType: 'indoor',
        poolType: 'recreational',
        accessibility: ['wheelchair', 'family-changing', 'accessible-parking'],
        amenities: ['parking', 'lockers', 'changing-rooms', 'cafe'],
        hours: [
          { dayOfWeek: 1, open: '06:00', close: '22:00', notes: 'Monday' },
          { dayOfWeek: 2, open: '06:00', close: '22:00', notes: 'Tuesday' },
          { dayOfWeek: 3, open: '06:00', close: '22:00', notes: 'Wednesday' },
          { dayOfWeek: 4, open: '06:00', close: '22:00', notes: 'Thursday' },
          { dayOfWeek: 5, open: '06:00', close: '22:00', notes: 'Friday' },
          { dayOfWeek: 6, open: '08:00', close: '18:00', notes: 'Saturday' },
          { dayOfWeek: 0, open: '08:00', close: '18:00', notes: 'Sunday' },
        ],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-002',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-002',
        name: 'YMCA of Greater New York - Brooklyn',
        address: {
          street: '357 Prospect Park West',
          city: 'Brooklyn',
          state: 'NY',
          zipCode: '11215',
          geographyId: 'brooklyn',
        },
        coordinates: { latitude: 40.6629, longitude: -73.9776 },
        facilityType: 'indoor',
        poolType: 'recreational',
        accessibility: ['wheelchair', 'family-changing'],
        amenities: ['parking', 'lockers', 'gym', 'cafe'],
        hours: [
          { dayOfWeek: 1, open: '05:30', close: '21:30' },
          { dayOfWeek: 2, open: '05:30', close: '21:30' },
          { dayOfWeek: 3, open: '05:30', close: '21:30' },
          { dayOfWeek: 4, open: '05:30', close: '21:30' },
          { dayOfWeek: 5, open: '05:30', close: '21:00' },
          { dayOfWeek: 6, open: '07:00', close: '19:00' },
          { dayOfWeek: 0, open: '08:00', close: '19:00' },
        ],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-003',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-003',
        name: 'JCC Manhattan - Kravis Center',
        address: {
          street: '334 Amsterdam Avenue',
          city: 'New York',
          state: 'NY',
          zipCode: '10023',
          geographyId: 'manhattan',
        },
        coordinates: { latitude: 40.7767, longitude: -73.9806 },
        facilityType: 'indoor',
        poolType: 'recreational',
        accessibility: ['wheelchair', 'family-changing'],
        amenities: ['lockers', 'changing-rooms', 'fitness-center'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-004',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-004',
        name: 'Asphalt Green - East Side Pool',
        address: {
          street: '555 East 90th Street',
          city: 'New York',
          state: 'NY',
          zipCode: '10128',
          geographyId: 'manhattan',
        },
        coordinates: { latitude: 40.7759, longitude: -73.9539 },
        facilityType: 'indoor',
        poolType: 'training',
        accessibility: ['wheelchair'],
        amenities: ['parking', 'lockers', 'cafe', 'fitness-center'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-005',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-005',
        name: 'Elite Swim Academy - Park Slope',
        address: {
          street: '718 Flatbush Avenue',
          city: 'Brooklyn',
          state: 'NY',
          zipCode: '11226',
          geographyId: 'brooklyn',
        },
        coordinates: { latitude: 40.6649, longitude: -73.9753 },
        facilityType: 'indoor',
        poolType: 'training',
        accessibility: ['wheelchair', 'family-changing'],
        amenities: ['lockers', 'changing-rooms', 'competitive-lanes'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-006',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-001',
        name: 'Astoria Pool - Queens',
        address: {
          street: '19-42 Astoria Park South',
          city: 'Queens',
          state: 'NY',
          zipCode: '11106',
          geographyId: 'queens',
        },
        coordinates: { latitude: 40.7614, longitude: -73.9254 },
        facilityType: 'outdoor',
        poolType: 'olympic',
        amenities: ['lockers', 'changing-rooms', 'parking'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-007',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-002',
        name: 'Red Hook Pool - Brooklyn',
        address: {
          street: '499 Columbia Street',
          city: 'Brooklyn',
          state: 'NY',
          zipCode: '11231',
          geographyId: 'brooklyn',
        },
        coordinates: { latitude: 40.6805, longitude: -74.0087 },
        facilityType: 'outdoor',
        poolType: 'recreational',
        amenities: ['lockers', 'changing-rooms', 'parking'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'loc-008',
        cityId: 'nyc',
        type: 'LocationDocument',
        providerId: 'prov-003',
        name: 'Chelsea Piers - Manhattan',
        address: {
          street: '62 Chelsea Piers',
          city: 'New York',
          state: 'NY',
          zipCode: '10011',
          geographyId: 'manhattan',
        },
        coordinates: { latitude: 40.7505, longitude: -74.0017 },
        facilityType: 'indoor',
        poolType: 'training',
        accessibility: ['wheelchair', 'family-changing'],
        amenities: ['parking', 'lockers', 'cafe', 'fitness-center', 'aquatic-facility'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];

    return locations;
  }

  /**
   * Get all mock programs across all locations
   */
  async getPrograms(): Promise<Program[]> {
    const programs: Program[] = [
      // Manhattan Programs
      {
        id: 'prog-001',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-001',
        locationId: 'loc-001',
        name: 'Parent-Child Swim (18mo-3yr)',
        description: 'Gentle introduction to water for toddlers with parent participation',
        ageMin: 18,
        ageMax: 36,
        skillLevel: 'beginner',
        sessionLengthMinutes: 30,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 120,
          max: 160,
          currency: 'USD',
          unit: 'program',
          notes: 'Resident discount available',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prog-002',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-001',
        locationId: 'loc-001',
        name: 'Preschool Swim (4-6yr)',
        description: 'Water safety and basic swimming fundamentals',
        ageMin: 48,
        ageMax: 72,
        skillLevel: 'beginner',
        sessionLengthMinutes: 45,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 160,
          max: 200,
          currency: 'USD',
          unit: 'program',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prog-003',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-001',
        locationId: 'loc-001',
        name: 'School Age Swim (7-10yr)',
        description: 'Intermediate swimming techniques and water safety',
        ageMin: 84,
        ageMax: 120,
        skillLevel: 'intermediate',
        sessionLengthMinutes: 60,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 200,
          max: 280,
          currency: 'USD',
          unit: 'program',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prog-004',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-001',
        locationId: 'loc-001',
        name: 'Teen Swim (11-14yr)',
        description: 'Advanced strokes and competitive swim preparation',
        ageMin: 132,
        ageMax: 168,
        skillLevel: 'advanced',
        sessionLengthMinutes: 60,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 240,
          max: 320,
          currency: 'USD',
          unit: 'program',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Brooklyn YMCA Programs
      {
        id: 'prog-005',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-002',
        locationId: 'loc-002',
        name: 'YMCA Aquatics - Tiny Swimmers (18mo-3yr)',
        description: 'Parent-child water exploration and comfort building',
        ageMin: 18,
        ageMax: 36,
        skillLevel: 'beginner',
        sessionLengthMinutes: 30,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 140,
          max: 180,
          currency: 'USD',
          unit: 'program',
          notes: 'YMCA members get 20% discount',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prog-006',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-002',
        locationId: 'loc-002',
        name: 'YMCA Aquatics - Level 1 (4-6yr)',
        description: 'Water safety, floating, and basic swimming skills',
        ageMin: 48,
        ageMax: 72,
        skillLevel: 'beginner',
        sessionLengthMinutes: 45,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 180,
          max: 220,
          currency: 'USD',
          unit: 'program',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prog-007',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-002',
        locationId: 'loc-007',
        name: 'Summer Swim Camp - Red Hook (7-10yr)',
        description: 'Intensive summer swim camp with daily sessions',
        ageMin: 84,
        ageMax: 120,
        skillLevel: 'all',
        sessionLengthMinutes: 90,
        totalSessions: 20,
        cadence: 'daily',
        priceRange: {
          min: 600,
          max: 800,
          currency: 'USD',
          unit: 'program',
          notes: 'Outdoor pool - weather dependent',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // JCC Manhattan Programs
      {
        id: 'prog-008',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-003',
        locationId: 'loc-003',
        name: 'JCC Parent-Child Swim (18mo-3yr)',
        description: 'Water comfort and bonding with professional instruction',
        ageMin: 18,
        ageMax: 36,
        skillLevel: 'beginner',
        sessionLengthMinutes: 30,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 180,
          max: 220,
          currency: 'USD',
          unit: 'program',
          notes: 'JCC members discounted',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prog-009',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-003',
        locationId: 'loc-008',
        name: 'Chelsea Piers Swim Academy - Intermediate (7-10yr)',
        description: 'Stroke refinement and endurance building',
        ageMin: 84,
        ageMax: 120,
        skillLevel: 'intermediate',
        sessionLengthMinutes: 60,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 280,
          max: 360,
          currency: 'USD',
          unit: 'program',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Asphalt Green Programs
      {
        id: 'prog-010',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-004',
        locationId: 'loc-004',
        name: 'Asphalt Green Swim Team - Competitive (11-14yr)',
        description: 'Training for competitive swimmers with meet preparation',
        ageMin: 132,
        ageMax: 168,
        skillLevel: 'advanced',
        prerequisites: ['Must complete intermediate swim level'],
        sessionLengthMinutes: 90,
        totalSessions: 12,
        cadence: 'weekly',
        priceRange: {
          min: 350,
          max: 450,
          currency: 'USD',
          unit: 'program',
          notes: 'Includes meet registration',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Elite Swim Academy Programs
      {
        id: 'prog-011',
        cityId: 'nyc',
        type: 'ProgramDocument',
        providerId: 'prov-005',
        locationId: 'loc-005',
        name: 'Elite Academy - Beginner (4-6yr)',
        description: 'Small group instruction with personalized attention',
        ageMin: 48,
        ageMax: 72,
        skillLevel: 'beginner',
        sessionLengthMinutes: 45,
        totalSessions: 8,
        cadence: 'weekly',
        priceRange: {
          min: 250,
          max: 350,
          currency: 'USD',
          unit: 'program',
          notes: 'Maximum 4 students per class',
        },
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];

    return programs;
  }

  /**
   * Get all mock sessions (enrollable instances)
   */
  async getSessions(filters?: SessionFilters): Promise<Session[]> {
    let sessions: Session[] = [
      // Hamilton Fish Pool - Parent-Child (Summer 2026)
      {
        id: 'sess-001',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-001',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-08',
        endDate: '2026-07-27',
        daysOfWeek: [1, 3, 5], // Mon, Wed, Fri
        timeOfDay: { start: '09:00', end: '09:30' },
        capacity: 12,
        enrolled: 8,
        availableSpots: 4,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-001',
        price: { amount: 150, currency: 'USD', notes: 'Resident rate' },
        searchTerms: 'parent child swim toddler manhattan water comfort',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-002',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-001',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-09',
        endDate: '2026-07-28',
        daysOfWeek: [2, 4], // Tue, Thu
        timeOfDay: { start: '10:00', end: '10:30' },
        capacity: 12,
        enrolled: 12,
        availableSpots: 0,
        registrationOpen: false,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-002',
        searchTerms: 'parent child swim toddler manhattan waitlist',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Hamilton Fish Pool - Preschool
      {
        id: 'sess-003',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-002',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-08',
        endDate: '2026-07-27',
        daysOfWeek: [1, 3, 5],
        timeOfDay: { start: '10:45', end: '11:30' },
        capacity: 15,
        enrolled: 9,
        availableSpots: 6,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-003',
        price: { amount: 175, currency: 'USD' },
        searchTerms: 'preschool swim 4-6 years manhattan beginner',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-004',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-002',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-09',
        endDate: '2026-07-28',
        daysOfWeek: [2, 4],
        timeOfDay: { start: '13:30', end: '14:15' },
        capacity: 15,
        enrolled: 14,
        availableSpots: 1,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-004',
        price: { amount: 175, currency: 'USD' },
        searchTerms: 'preschool swim 4-6 years afternoon manhattan',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Hamilton Fish Pool - School Age
      {
        id: 'sess-005',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-003',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-08',
        endDate: '2026-07-27',
        daysOfWeek: [1, 3, 5],
        timeOfDay: { start: '15:00', end: '16:00' },
        capacity: 18,
        enrolled: 12,
        availableSpots: 6,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-005',
        price: { amount: 240, currency: 'USD' },
        searchTerms: 'school age swim 7-10 years afternoon manhattan intermediate',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-006',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-003',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-09',
        endDate: '2026-07-28',
        daysOfWeek: [2, 4],
        timeOfDay: { start: '16:15', end: '17:15' },
        capacity: 18,
        enrolled: 7,
        availableSpots: 11,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-006',
        price: { amount: 240, currency: 'USD' },
        searchTerms: 'school age swim 7-10 years evening manhattan intermediate',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Hamilton Fish Pool - Teen
      {
        id: 'sess-007',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-004',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-08',
        endDate: '2026-07-27',
        daysOfWeek: [1, 3, 5],
        timeOfDay: { start: '17:30', end: '18:30' },
        capacity: 16,
        enrolled: 10,
        availableSpots: 6,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-007',
        price: { amount: 280, currency: 'USD' },
        searchTerms: 'teen swim 11-14 years advanced manhattan competitive',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // YMCA Brooklyn - Tiny Swimmers
      {
        id: 'sess-008',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-005',
        providerId: 'prov-002',
        locationId: 'loc-002',
        startDate: '2026-06-10',
        endDate: '2026-07-29',
        daysOfWeek: [3, 5], // Wed, Fri
        timeOfDay: { start: '09:30', end: '10:00' },
        capacity: 10,
        enrolled: 8,
        availableSpots: 2,
        registrationOpen: true,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-008',
        price: { amount: 160, currency: 'USD', notes: 'Member: $128' },
        searchTerms: 'YMCA parent child toddler brooklyn water',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-009',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-005',
        providerId: 'prov-002',
        locationId: 'loc-002',
        startDate: '2026-06-11',
        endDate: '2026-07-30',
        daysOfWeek: [3, 5],
        timeOfDay: { start: '10:15', end: '10:45' },
        capacity: 10,
        enrolled: 5,
        availableSpots: 5,
        registrationOpen: true,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-009',
        price: { amount: 160, currency: 'USD' },
        searchTerms: 'YMCA parent child toddler brooklyn afternoon',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // YMCA Brooklyn - Level 1
      {
        id: 'sess-010',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-006',
        providerId: 'prov-002',
        locationId: 'loc-002',
        startDate: '2026-06-10',
        endDate: '2026-07-29',
        daysOfWeek: [2, 4], // Tue, Thu
        timeOfDay: { start: '14:00', end: '14:45' },
        capacity: 14,
        enrolled: 14,
        availableSpots: 0,
        registrationOpen: false,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-010',
        price: { amount: 200, currency: 'USD' },
        searchTerms: 'YMCA level 1 swim 4-6 years brooklyn waitlist',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-011',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-006',
        providerId: 'prov-002',
        locationId: 'loc-002',
        startDate: '2026-06-11',
        endDate: '2026-07-30',
        daysOfWeek: [2, 4],
        timeOfDay: { start: '15:00', end: '15:45' },
        capacity: 14,
        enrolled: 8,
        availableSpots: 6,
        registrationOpen: true,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-011',
        price: { amount: 200, currency: 'USD' },
        searchTerms: 'YMCA level 1 swim 4-6 years brooklyn beginner',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Red Hook Summer Camp
      {
        id: 'sess-012',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-007',
        providerId: 'prov-002',
        locationId: 'loc-007',
        startDate: '2026-06-22',
        endDate: '2026-08-01',
        daysOfWeek: [1, 2, 3, 4, 5], // Mon-Fri
        timeOfDay: { start: '09:00', end: '10:30' },
        capacity: 20,
        enrolled: 18,
        availableSpots: 2,
        registrationOpen: true,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-012',
        price: { amount: 750, currency: 'USD', notes: 'Member: $600' },
        searchTerms: 'summer camp intensive swim brooklyn outdoor',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-013',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-007',
        providerId: 'prov-002',
        locationId: 'loc-007',
        startDate: '2026-07-06',
        endDate: '2026-08-14',
        daysOfWeek: [1, 2, 3, 4, 5],
        timeOfDay: { start: '10:45', end: '12:15' },
        capacity: 20,
        enrolled: 11,
        availableSpots: 9,
        registrationOpen: true,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-013',
        price: { amount: 750, currency: 'USD' },
        searchTerms: 'summer camp swim brooklyn afternoon outdoor',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // JCC Manhattan - Parent-Child
      {
        id: 'sess-014',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-008',
        providerId: 'prov-003',
        locationId: 'loc-003',
        startDate: '2026-06-08',
        endDate: '2026-07-27',
        daysOfWeek: [1, 4], // Mon, Thu
        timeOfDay: { start: '09:15', end: '09:45' },
        capacity: 12,
        enrolled: 11,
        availableSpots: 1,
        registrationOpen: true,
        registrationUrl: 'https://jccmanhattan.org/register?session=sess-014',
        price: { amount: 200, currency: 'USD', notes: 'JCC Member: $160' },
        searchTerms: 'JCC parent child swim manhattan toddler',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Chelsea Piers - Intermediate
      {
        id: 'sess-015',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-009',
        providerId: 'prov-003',
        locationId: 'loc-008',
        startDate: '2026-06-09',
        endDate: '2026-07-28',
        daysOfWeek: [2, 4], // Tue, Thu
        timeOfDay: { start: '15:30', end: '16:30' },
        capacity: 16,
        enrolled: 13,
        availableSpots: 3,
        registrationOpen: true,
        registrationUrl: 'https://chelseapiers.com/register?session=sess-015',
        price: { amount: 320, currency: 'USD' },
        searchTerms: 'Chelsea Piers swim intermediate 7-10 manhattan',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-016',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-009',
        providerId: 'prov-003',
        locationId: 'loc-008',
        startDate: '2026-06-10',
        endDate: '2026-07-29',
        daysOfWeek: [3, 5, 6], // Wed, Fri, Sat
        timeOfDay: { start: '10:00', end: '11:00' },
        capacity: 16,
        enrolled: 6,
        availableSpots: 10,
        registrationOpen: true,
        registrationUrl: 'https://chelseapiers.com/register?session=sess-016',
        price: { amount: 320, currency: 'USD' },
        searchTerms: 'Chelsea Piers swim intermediate 7-10 weekend',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Asphalt Green - Competitive Team
      {
        id: 'sess-017',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-010',
        providerId: 'prov-004',
        locationId: 'loc-004',
        startDate: '2026-06-08',
        endDate: '2026-08-24',
        daysOfWeek: [1, 2, 3, 4, 5], // Mon-Fri
        timeOfDay: { start: '16:30', end: '18:00' },
        capacity: 20,
        enrolled: 19,
        availableSpots: 1,
        registrationOpen: true,
        registrationUrl: 'https://asphaltgreen.org/register?session=sess-017',
        price: { amount: 400, currency: 'USD', notes: 'Includes meets' },
        searchTerms: 'Asphalt Green competitive swim team 11-14 manhattan advanced',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-018',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-010',
        providerId: 'prov-004',
        locationId: 'loc-004',
        startDate: '2026-06-08',
        endDate: '2026-08-24',
        daysOfWeek: [1, 2, 3, 4, 5],
        timeOfDay: { start: '18:15', end: '19:45' },
        capacity: 18,
        enrolled: 14,
        availableSpots: 4,
        registrationOpen: true,
        registrationUrl: 'https://asphaltgreen.org/register?session=sess-018',
        price: { amount: 400, currency: 'USD' },
        searchTerms: 'Asphalt Green competitive swim team evening 11-14 advanced',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Astoria Pool - Queens (Outdoor)
      {
        id: 'sess-019',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-002',
        providerId: 'prov-001',
        locationId: 'loc-006',
        startDate: '2026-06-22',
        endDate: '2026-08-31',
        daysOfWeek: [2, 4], // Tue, Thu (summer outdoor)
        timeOfDay: { start: '10:00', end: '10:45' },
        capacity: 20,
        enrolled: 15,
        availableSpots: 5,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-019',
        price: { amount: 150, currency: 'USD', notes: 'Outdoor pool - weather dependent' },
        searchTerms: 'preschool swim queens astoria outdoor 4-6',
        geographyIds: ['queens'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-020',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-003',
        providerId: 'prov-001',
        locationId: 'loc-006',
        startDate: '2026-06-22',
        endDate: '2026-08-31',
        daysOfWeek: [1, 3, 5],
        timeOfDay: { start: '14:00', end: '15:00' },
        capacity: 25,
        enrolled: 17,
        availableSpots: 8,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-020',
        price: { amount: 200, currency: 'USD' },
        searchTerms: 'school age swim queens astoria 7-10 outdoor',
        geographyIds: ['queens'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Elite Swim Academy - Brooklyn
      {
        id: 'sess-021',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-011',
        providerId: 'prov-005',
        locationId: 'loc-005',
        startDate: '2026-06-08',
        endDate: '2026-07-27',
        daysOfWeek: [1, 3, 5],
        timeOfDay: { start: '10:00', end: '10:45' },
        capacity: 4,
        enrolled: 4,
        availableSpots: 0,
        registrationOpen: false,
        registrationUrl: 'https://eliteswimacademy.com/register?session=sess-021',
        price: { amount: 320, currency: 'USD', notes: 'Small group - waiting list only' },
        searchTerms: 'Elite Swim Academy beginner brooklyn 4-6 small group',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-022',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-011',
        providerId: 'prov-005',
        locationId: 'loc-005',
        startDate: '2026-06-09',
        endDate: '2026-07-28',
        daysOfWeek: [2, 4],
        timeOfDay: { start: '14:30', end: '15:15' },
        capacity: 4,
        enrolled: 3,
        availableSpots: 1,
        registrationOpen: true,
        registrationUrl: 'https://eliteswimacademy.com/register?session=sess-022',
        price: { amount: 320, currency: 'USD' },
        searchTerms: 'Elite Swim Academy beginner brooklyn afternoon 4-6',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-023',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-011',
        providerId: 'prov-005',
        locationId: 'loc-005',
        startDate: '2026-06-10',
        endDate: '2026-07-29',
        daysOfWeek: [3, 5],
        timeOfDay: { start: '16:00', end: '16:45' },
        capacity: 4,
        enrolled: 2,
        availableSpots: 2,
        registrationOpen: true,
        registrationUrl: 'https://eliteswimacademy.com/register?session=sess-023',
        price: { amount: 320, currency: 'USD' },
        searchTerms: 'Elite Swim Academy beginner brooklyn evening 4-6 small group',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-024',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-011',
        providerId: 'prov-005',
        locationId: 'loc-005',
        startDate: '2026-06-13',
        endDate: '2026-07-25',
        daysOfWeek: [6], // Saturday
        timeOfDay: { start: '09:00', end: '09:45' },
        capacity: 4,
        enrolled: 4,
        availableSpots: 0,
        registrationOpen: false,
        registrationUrl: 'https://eliteswimacademy.com/register?session=sess-024',
        price: { amount: 320, currency: 'USD' },
        searchTerms: 'Elite Swim Academy beginner brooklyn weekend saturday 4-6',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-025',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-011',
        providerId: 'prov-005',
        locationId: 'loc-005',
        startDate: '2026-06-14',
        endDate: '2026-07-26',
        daysOfWeek: [0], // Sunday
        timeOfDay: { start: '10:30', end: '11:15' },
        capacity: 4,
        enrolled: 1,
        availableSpots: 3,
        registrationOpen: true,
        registrationUrl: 'https://eliteswimacademy.com/register?session=sess-025',
        price: { amount: 320, currency: 'USD' },
        searchTerms: 'Elite Swim Academy beginner brooklyn sunday 4-6',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      // Additional weekend sessions
      {
        id: 'sess-026',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-002',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-13',
        endDate: '2026-08-01',
        daysOfWeek: [6], // Saturday
        timeOfDay: { start: '09:00', end: '09:45' },
        capacity: 15,
        enrolled: 11,
        availableSpots: 4,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-026',
        price: { amount: 175, currency: 'USD' },
        searchTerms: 'weekend swim preschool saturday manhattan 4-6',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-027',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-003',
        providerId: 'prov-001',
        locationId: 'loc-001',
        startDate: '2026-06-14',
        endDate: '2026-08-02',
        daysOfWeek: [0], // Sunday
        timeOfDay: { start: '11:00', end: '12:00' },
        capacity: 18,
        enrolled: 8,
        availableSpots: 10,
        registrationOpen: true,
        registrationUrl: 'https://nycparks.org/swim/register?session=sess-027',
        price: { amount: 240, currency: 'USD' },
        searchTerms: 'weekend swim school age sunday manhattan 7-10',
        geographyIds: ['manhattan'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sess-028',
        cityId: 'nyc',
        type: 'SessionDocument',
        programId: 'prog-006',
        providerId: 'prov-002',
        locationId: 'loc-002',
        startDate: '2026-06-13',
        endDate: '2026-08-01',
        daysOfWeek: [6], // Saturday
        timeOfDay: { start: '13:00', end: '13:45' },
        capacity: 14,
        enrolled: 9,
        availableSpots: 5,
        registrationOpen: true,
        registrationUrl: 'https://ymcanyc.org/register?session=sess-028',
        price: { amount: 200, currency: 'USD', notes: 'Member: $160' },
        searchTerms: 'YMCA level 1 swim saturday brooklyn 4-6',
        geographyIds: ['brooklyn'],
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        lastSyncedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];

    // Apply filters if provided
    if (filters) {
      if (filters.startDate) {
        sessions = sessions.filter((s) => s.startDate >= filters.startDate!);
      }
      if (filters.endDate) {
        sessions = sessions.filter((s) => s.endDate <= filters.endDate!);
      }
      if (filters.geographyIds && filters.geographyIds.length > 0) {
        sessions = sessions.filter((s) =>
          s.geographyIds.some((g) => filters.geographyIds!.includes(g))
        );
      }
      if (filters.providerIds && filters.providerIds.length > 0) {
        sessions = sessions.filter((s) => filters.providerIds!.includes(s.providerId));
      }
    }

    return sessions;
  }

  /**
   * Get provider signup URL for a session
   */
  getProviderSignupUrl(session: Session): string {
    return session.registrationUrl || `https://nycparks.org/swim/signup?sessionId=${session.id}`;
  }

  /**
   * Estimate transit time from origin to destination
   * Uses haversine distance fallback since this is mock data without MTA integration
   */
  async getTransitEstimate(
    origin: Coordinates,
    destination: Coordinates,
    mode: TransitMode
  ): Promise<TransitEstimate | null> {
    const distance = this.calculateDistance(origin, destination);

    let durationMinutes: number;

    // Estimate based on mode of travel
    switch (mode.mode) {
      case 'walking':
        durationMinutes = this.estimateWalkingTime(distance);
        break;
      case 'subway':
        // Rough estimate: average NYC subway is about 15 mph including stations
        durationMinutes = Math.ceil((distance / 15) * 60) + 5; // +5 min for station time
        break;
      case 'bus':
        // Buses average 8-10 mph in NYC
        durationMinutes = Math.ceil((distance / 8) * 60) + 3;
        break;
      case 'biking':
        // Average biking 12 mph
        durationMinutes = Math.ceil((distance / 12) * 60);
        break;
      case 'driving':
        // Average driving in NYC 12 mph during busy times
        durationMinutes = Math.ceil((distance / 12) * 60);
        break;
      default:
        durationMinutes = this.estimateWalkingTime(distance);
    }

    return {
      durationMinutes,
      distance,
      mode: mode.mode,
      confidence: 'fallback',
      calculatedAt: new Date().toISOString(),
    };
  }

  /**
   * Sync data to Cosmos DB
   * Mock adapter just logs - doesn't actually sync
   */
  async syncData(): Promise<SyncResult> {
    console.log(
      '[NYC Mock Adapter] Sync requested - mock data always fresh, no actual sync needed'
    );

    const locations = await this.getLocations();
    const programs = await this.getPrograms();
    const sessions = await this.getSessions();

    const totalRecords = locations.length + programs.length + sessions.length;

    return {
      success: true,
      recordsProcessed: totalRecords,
      recordsCreated: 0,
      recordsUpdated: totalRecords,
      errors: [],
      syncedAt: new Date().toISOString(),
    };
  }

  /**
   * Validate adapter configuration
   */
  async validateConfig(): Promise<ValidationResult> {
    return {
      valid: true,
      errors: [],
      warnings: [
        'NYC Mock Adapter: Using hardcoded demo data. Not suitable for production.',
        'Confidence level set to "medium" - actual NYC Parks data would have higher confidence.',
      ],
    };
  }

  /**
   * Get list of hardcoded providers
   */
  async getProviders(): Promise<Provider[]> {
    const providers: Provider[] = [
      {
        id: 'prov-001',
        cityId: 'nyc',
        type: 'ProviderDocument',
        name: 'NYC Parks & Recreation',
        description: 'City-run aquatics programs across NYC',
        website: 'https://nycparks.org/swim',
        phone: '(212) 360-3514',
        email: 'swim@nycparks.org',
        providerType: 'public',
        verified: true,
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prov-002',
        cityId: 'nyc',
        type: 'ProviderDocument',
        name: 'YMCA of Greater New York',
        description: 'Community-based aquatics and wellness programs',
        website: 'https://ymcanyc.org',
        phone: '(212) 615-9600',
        email: 'programs@ymcanyc.org',
        providerType: 'ymca',
        verified: true,
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prov-003',
        cityId: 'nyc',
        type: 'ProviderDocument',
        name: 'JCC Manhattan',
        description: 'Jewish Community Center providing aquatic education',
        website: 'https://jccmanhattan.org',
        phone: '(646) 505-4444',
        email: 'aquatics@jccmanhattan.org',
        providerType: 'nonprofit',
        verified: true,
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prov-004',
        cityId: 'nyc',
        type: 'ProviderDocument',
        name: 'Asphalt Green',
        description: 'Nonprofit providing aquatics and sports programs for youth',
        website: 'https://asphaltgreen.org',
        phone: '(212) 369-8890',
        email: 'aquatics@asphaltgreen.org',
        providerType: 'nonprofit',
        verified: true,
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'prov-005',
        cityId: 'nyc',
        type: 'ProviderDocument',
        name: 'Elite Swim Academy',
        description: 'Private swim school specializing in small group instruction',
        website: 'https://eliteswimacademy.com',
        phone: '(718) 555-0123',
        email: 'info@eliteswimacademy.com',
        providerType: 'private',
        verified: false,
        confidence: 'medium',
        sourceSystem: 'nyc-mock-data',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];

    return providers;
  }
}
